const team={view:'week',employees:[{name:'Maui',hours:38,advance:25000,paid:180000},{name:'Hina',hours:35,advance:15000,paid:165000},{name:'Tane',hours:32,advance:10000,paid:142000},{name:'Moana',hours:28,advance:0,paid:118000}]};
const viewCopy={week:['Semaine','Une ligne par salarié. Les chiffres importants restent visibles immédiatement.'],pay:['Paiements','Total payé et reste à vérifier, sans information de chantier.'],advance:['Acomptes','Suivi rapide des avances versées cette semaine.']};
document.addEventListener('DOMContentLoaded',()=>{bind();tick();setInterval(tick,30000);render()});
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{team.view=b.dataset.view;render()}));addEmployee.addEventListener('click',()=>employeeSheet.classList.add('open'));closeEmployee.addEventListener('click',()=>employeeSheet.classList.remove('open'));employeeForm.addEventListener('submit',saveEmployee)}
function tick(){teamClock.textContent=new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long'})+' - '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===team.view));viewTitle.textContent=viewCopy[team.view][0];viewIntro.textContent=viewCopy[team.view][1];renderMetrics();teamContent.innerHTML=`<section class="panel"><div class="list">${team.employees.map(row).join('')}</div></section>`}
function renderMetrics(){const hours=sum('hours');const advances=sum('advance');const paid=sum('paid');teamMetrics.innerHTML=`<article class="metric"><span>Salariés</span><strong>${team.employees.length}</strong></article><article class="metric"><span>Heures</span><strong>${hours}</strong></article><article class="metric"><span>Payé</span><strong>${money(paid)}</strong></article>`}
function row(e){if(team.view==='advance')return `<article class="employee"><div><h3>${esc(e.name)}</h3><p>Acompte versé cette semaine</p><span class="chip warn">${money(e.advance)}</span></div><div class="amount"><strong>${money(e.advance)}</strong></div></article>`;if(team.view==='pay')return `<article class="employee"><div><h3>${esc(e.name)}</h3><p>${e.hours}h saisies · acompte ${money(e.advance)}</p><span class="chip ok">Total payé</span></div><div class="amount"><strong>${money(e.paid)}</strong></div></article>`;return `<article class="employee"><div><h3>${esc(e.name)}</h3><p>${e.hours}h · acompte ${money(e.advance)}</p><span class="chip ok">Total payé ${money(e.paid)}</span></div><div class="amount"><strong>${e.hours}h</strong></div></article>`}
function saveEmployee(e){e.preventDefault();team.employees.unshift({name:employeeName.value,hours:Number(employeeHours.value)||0,advance:Number(employeeAdvance.value)||0,paid:Number(employeePaid.value)||0});employeeForm.reset();employeeSheet.classList.remove('open');render()}
function sum(key){return team.employees.reduce((total,e)=>total+Number(e[key]||0),0)}
function money(v){return new Intl.NumberFormat('fr-FR').format(v)+' F'}
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}