const defaultWeatherConfig={provider:'open-meteo',endpoint:'https://api.open-meteo.com/v1/forecast',latitude:-17.552554,longitude:-149.607182,timezone:'Pacific/Tahiti',forecastDays:3,timeoutMs:8000,refreshIntervalMs:900000,current:['temperature_2m','relative_humidity_2m','precipitation','rain','weather_code','cloud_cover','wind_speed_10m','wind_gusts_10m'],hourly:['temperature_2m','relative_humidity_2m','precipitation_probability','wind_speed_10m'],daily:['weather_code','temperature_2m_max','temperature_2m_min','precipitation_probability_max','wind_speed_10m_max'],units:{temperature:'celsius',windSpeed:'kmh',precipitation:'mm'},chantierThresholds:{idealRainRiskMax:30,warningRainRiskMax:60,idealWindMaxKmh:25,warningWindMaxKmh:40,unsafeGustMinKmh:55,activeRainUnsafeMm:5}};
function getWeatherConfig(){return{...defaultWeatherConfig,...(window.AUREL_CONFIG&&window.AUREL_CONFIG.weather?window.AUREL_CONFIG.weather:{})}}
function initWeather(){refreshWeather();setInterval(refreshWeather,getWeatherConfig().refreshIntervalMs)}
async function refreshWeather(){try{const data=await getWeatherData();renderWeather(data);renderTomorrowForecast(data.tomorrow)}catch(error){console.warn('Erreur météo',error);renderWeatherError()}}
async function getWeatherData(){const c=getWeatherConfig();const params=new URLSearchParams({latitude:c.latitude,longitude:c.longitude,current:c.current.join(','),hourly:c.hourly.join(','),daily:c.daily.join(','),timezone:c.timezone,forecast_days:c.forecastDays,temperature_unit:c.units.temperature,wind_speed_unit:c.units.windSpeed,precipitation_unit:c.units.precipitation});const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),c.timeoutMs);const response=await fetch(c.endpoint+'?'+params.toString(),{signal:controller.signal}).finally(()=>clearTimeout(timer));if(!response.ok)throw new Error('Open-Meteo '+response.status);return mapWeather(await response.json(),c)}
function mapWeather(api,c){const cur=api.current||{};const daily=api.daily||{};const rainRisk=value(daily.precipitation_probability_max,0);const rain=cur.rain||cur.precipitation||0;const chantier=chantierStatus({rainRisk,windSpeed:cur.wind_speed_10m,windGusts:cur.wind_gusts_10m,rain},c.chantierThresholds);return{temperature:fmt(cur.temperature_2m,'°C'),humidity:fmt(cur.relative_humidity_2m,'%'),rainRisk:fmt(rainRisk,'%'),wind:fmt(cur.wind_speed_10m,' km/h'),conditions:weatherCode(cur.weather_code),chantier,tomorrow:tomorrow(api)}}
function tomorrow(api){const d=api.daily||{},h=api.hourly||{},date=value(d.time,1),hours=[];if(date&&Array.isArray(h.time)){[6,9,12,15,18].forEach(hour=>{const i=h.time.indexOf(date+'T'+String(hour).padStart(2,'0')+':00');if(i>=0)hours.push({hour:String(hour).padStart(2,'0')+'h',temperature:fmt(value(h.temperature_2m,i),'°C'),rain:fmt(value(h.precipitation_probability,i),'%'),wind:fmt(value(h.wind_speed_10m,i),' km/h')})})}return{min:fmt(value(d.temperature_2m_min,1),'°C'),max:fmt(value(d.temperature_2m_max,1),'°C'),rain:fmt(value(d.precipitation_probability_max,1),'%'),wind:fmt(value(d.wind_speed_10m_max,1),' km/h'),hours}}
function renderWeather(data){const rows=[['Conditions chantier',statusLabel(data.chantier)],['Température',data.temperature],['Pluie',data.rainRisk],['Vent',data.wind],['Humidité',data.humidity],['Ciel',data.conditions]];weather.innerHTML=rows.map(r=>`<article class="weather-row"><span>${esc(r[0])}</span><strong>${esc(r[1])}</strong></article>`).join('');window.AurelState=window.AurelState||{};window.AurelState.weather={raw:data,status:'ready',summary:'Conditions chantier : '+statusLabel(data.chantier)}}
function renderTomorrowForecast(t){if(!t){tomorrowForecast.textContent='Prévisions indisponibles.';return}tomorrowForecast.innerHTML=`<div class="forecast-grid"><article class="forecast-card"><span>Minimum</span><strong>${esc(t.min)}</strong></article><article class="forecast-card"><span>Maximum</span><strong>${esc(t.max)}</strong></article><article class="forecast-card"><span>Pluie</span><strong>${esc(t.rain)}</strong></article><article class="forecast-card"><span>Vent</span><strong>${esc(t.wind)}</strong></article></div><div class="forecast-hours">${t.hours.map(h=>`<article class="forecast-hour"><span>${esc(h.hour)}</span><strong>${esc(h.temperature)}</strong><small>Pluie ${esc(h.rain)} · Vent ${esc(h.wind)}</small></article>`).join('')||'<article class="forecast-card">Evolution horaire indisponible.</article>'}</div>`}
function renderWeatherError(){weather.innerHTML='<article class="weather-row"><span>Météo</span><strong>Indisponible</strong></article>';renderTomorrowForecast(null)}
function value(arr,i){return Array.isArray(arr)?arr[i]:null}function fmt(v,u){return v===null||v===undefined||Number.isNaN(v)?'Indisponible':Math.round(v)+u}
function chantierStatus(w,t){const s={...defaultWeatherConfig.chantierThresholds,...(t||{})};if(w.rainRisk>s.warningRainRiskMax||w.windSpeed>s.warningWindMaxKmh||w.windGusts>=s.unsafeGustMinKmh||w.rain>=s.activeRainUnsafeMm)return'unsafe';if(w.rainRisk>s.idealRainRiskMax||w.windSpeed>s.idealWindMaxKmh)return'warning';return'ideal'}
function statusLabel(s){return{ideal:'Idéales',warning:'Vigilance',unsafe:'Déconseillées'}[s]||'Vigilance'}
function weatherCode(code){return{0:'Ciel dégagé',1:'Principalement clair',2:'Partiellement nuageux',3:'Couvert',45:'Brouillard',51:'Bruine légère',61:'Pluie faible',63:'Pluie modérée',65:'Forte pluie',80:'Averses faibles',81:'Averses modérées',95:'Orage'}[code]||'Conditions inconnues'}
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function initAurel(mods){mods.forEach(name=>{if(typeof window[name]==='function'){try{window[name]()}catch(e){console.warn(name,e)}}})}
initAurel(['initWebcam','initClock','initRadar','initWeather']);